language: perl
perl:
  - 5.12
  - 5.14
  - 5.16
  - 5.18
notifications:
  email:
    - tf.900913@gmail.com
script:
  - prove -lr t
install:
  - "cpanm --notest Module::Build ExtUtils::ParseXS"
  - "cpanm --with-recommends --with-suggests --installdeps --notest ."